FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY hound_forward ./hound_forward
COPY db ./db

CMD ["uvicorn", "hound_forward.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
