FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY hound_forward ./hound_forward
COPY db ./db

CMD ["python", "-m", "hound_forward.agent.main"]
